sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"
app_admin_brand.brand_create:
        path: /admin/brand/create
        controller: App\Controller\Admin\BrandController::create
        methods: [ GET, POST ]
